"""Migration part 2

Revision ID: aa672d356dd3
Revises: 
Create Date: 2023-08-25 14:04:16.334222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa672d356dd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary_schools')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint('schools_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_unique_constraint('schools_name_key', ['name'])

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('likes')

    op.create_table('secondary_schools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='secondary_schools_pkey'),
    sa.UniqueConstraint('code', name='secondary_schools_code_key'),
    sa.UniqueConstraint('name', name='secondary_schools_name_key')
    )
    # ### end Alembic commands ###
