name: Feature Request
description: Request a new feature or enhancement
title: "[FEATURE REQUEST]: "
labels: ["feature request", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit your feature request to help us improve **dijidaro**. Please fill in all fields to the best of your ability.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and detailed description of the feature you are requesting. Explain why you believe it would be valuable to have this feature added to the project.
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be beneficial. Provide examples or explain the problem you are trying to solve.
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: If you have any ideas or suggestions for how this feature could be implemented, please provide them here. Include any relevant technical details or considerations.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives or workarounds? If so, please describe them here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://dijidaro.co.ke/terms)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
